sudo: required
language: generic

env:
    - SINGULARITY_VERSION=2.4

before_install:
    - wget https://github.com/singularityware/singularity/releases/download/$SINGULARITY_VERSION/singularity-$SINGULARITY_VERSION.tar.gz
    - tar xvf singularity-$SINGULARITY_VERSION.tar.gz
    - pushd singularity-$SINGULARITY_VERSION
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - popd

script:
    - ./remoll-run.sh runexample.mac
